[package]
name = "coerce"
description = "Async actor runtime and distributed systems framework"
license = "Apache-2.0"
version = "0.6.0"
authors = ["Leon Hartley <ljph@outlook.com>"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/leonhartley/coerce-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }
tokio-stream = { version = "0.1" }
uuid = { version = "0.8", features = ["serde", "v4"] }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
futures = "0.3.12"
async-trait = { version = "0.1" }
hashring = "0.2.0"
bytes = "1.1"
byteorder = "1.4"
chrono = "0.4"
protobuf = "2.27.1"
tracing = "0.1"
tracing-futures = "0.2.5"
tracing-opentelemetry = "0.17.2"
opentelemetry = { version = "0.17.0", default-features = false, features = ["trace"] }
async-raft = "0.6"
memstore = "0.2"
anyhow = "1.0"
rand = "0.8.5"
parking_lot = "0.12"
axum = "0.5.6"
axum-extra = "0.3.3"
metrics = "0.18.1"

## todo: Add back when they release the version with updated tokio
#trust-dns-proto = { version = "0.19", features = ["tokio-runtime"] }
#trust-dns-client = { version = "0.19" }

[dev-dependencies]
env_logger = "0.9"
coerce-macros = { path = "./macros" }
tracing-subscriber = "0.3.9"
opentelemetry-jaeger = "0.16.0"
criterion = { version = "0.3", features = ["async_tokio"] }

[[bench]]
name = "actor_messaging"
harness = false