[package]
name = "coerce"
description = "Async actor runtime and distributed systems framework"
license = "Apache-2.0"
version = "0.3.1-prerelease"
authors = ["Leon Hartley <ljph@outlook.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/leonhartley/coerce-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-util = { version = "0.6", features = ["full"] }
tokio-stream = { version = "0.1"}
uuid = { version = "0.8", features = ["serde", "v4"] }
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
futures = "0.3.1"
async-trait = { version = "0.1" }
hashring = "0.2.0"
bytes = "1.0"
byteorder = "1.3.4"
chrono = "0.4"
bincode = "1.3"
protobuf = "2.18.1"

## todo: Add back when they release the version with updated tokio
#trust-dns-proto = { version = "0.19", features = ["tokio-runtime"] }
#trust-dns-client = { version = "0.19" }

[dev-dependencies]
env_logger = "0.7.1"
coerce-macros = { path = "./macros" }


[build-dependencies]
protobuf-codegen-pure = "2.18.1"