[workspace]
members = [
    "coerce",
    "coerce/macros",
#    "coerce-remote/providers/coerce-mysql",
    "providers/coerce-redis",
    "examples/coerce-chat-common",
    "examples/coerce-chat-worker",
    "examples/coerce-chat-gateway"
]
