[workspace]
members = [
    "coerce-rt",
    "coerce-rt/macros",
    "providers/coerce-redis",
    "examples/coerce-chat-common",
    "examples/coerce-chat-worker",
    "examples/coerce-chat-gateway"
]
