[package]
name = "coerce-chat-gateway"
version = "0.1.0"
authors = ["Leon Hartley <leon.hartley@sharpgaming.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
