apiVersion: v1
kind: ServiceAccount
metadata:
  name: sharded-chat-server
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "list" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: sharded-chat-server
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io