[package]
name = "coerce-redis"
version = "0.3.0"
authors = ["Leon Hartley <ljph@outlook.com>"]
edition = "2021"
description = "Redis actor persistence provider for Coerce. Supports event sourcing and snapshots"
license = "Apache-2.0"
repository = "https://github.com/leonhartley/coerce-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
coerce = { version = "0.7.0" }
async-trait = { version = "0.1" }
redis = { version = "0.21", features = ["tokio-comp", "cluster"] }
redis_cluster_async = "0.7.0"
tokio = { version = "1.20.1", features = ["full"] }
anyhow = "1"
bytes = { version = "1.2.1" }