on:
  push:
    branches:
      - master
      - feature/**
      - dev
name: coerce-rs tests

jobs:
  build_and_test:
    name: Coerce Runtime Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: supercharge/redis-github-action@1.2.0
        with:
          redis-version: 6
      - uses: actions-rs/cargo@v1
        with:
          command: test --all-features
